version: '3.4'

services:
  simp.bootstrapper:
    image: ${DOCKER_REGISTRY-}simpbootstrapper
    container_name: simpbootstrapper
    build:
      context: .
      dockerfile: src/Bootstrapper/Simp.Bootstrapper/Dockerfile
    networks:
     - simp

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssql
    ports:
      - 1433:1433
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    networks:
      - simp

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    hostname: rmq
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management UI port
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    networks:
      - simp

  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
      - Seq__Internal__Storage__Type=MSSQLServer
      - Seq__Internal__Storage__ConnectionString=Server=mssql;Database=seq;User Id=sa;Password=Pass@word;
    depends_on:
      - sqlserver
    networks:
      - simp

networks:
  simp:
    driver: bridge
