name: Build and Test

on:
  push:
    branches:
      - docker-hub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
      
      - name: Restore dependencies
        run: dotnet restore ./src/Bootstrapper/Simp.Bootstrapper/Simp.Bootstrapper.csproj
      
      - name: Build
        run: dotnet build ./src/Bootstrapper/Simp.Bootstrapper/Simp.Bootstrapper.csproj --configuration Release
      
      - name: Test
        run: dotnet test ./tests/Simp.IntegrationTests/Simp.IntegrationTests.csproj

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build -f ./src/Bootstrapper/Simp.Bootstrapper/Dockerfile -t trongchuannguyen/simp:latest .

      - name: Push the Docker image
        run: docker push trongchuannguyen/simp:latest
