name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
      
      - name: Restore dependencies
        run: dotnet restore ./src/Bootstrapper/Simp.Bootstrapper/Simp.Bootstrapper.csproj
      
      - name: Build
        run: dotnet build --configuration Release
      
      - name: Test
        run: dotnet test ./tests/Simp.IntegrationTests/Simp.IntegrationTests.csproj
